In [1]:
import selenium
import pickle
import basketball
import requests

import pandas as pd

from bs4 import BeautifulSoup

In [5]:
with open('database.pickle', 'rb') as f:
    database = pickle.load(f)
    
teams = list(database.keys())
print(teams)

['MIA', 'ORL', 'PHI', 'NYK', 'BOS', 'WAS', 'NJN', 'IND', 'ATL', 'DET', 'MIL', 'CHH', 'TOR', 'CLE', 'CHI', 'SAS', 'UTA', 'HOU', 'MIN', 'DAL', 'DEN', 'VAN', 'POR', 'LAL', 'PHO', 'SAC', 'SEA', 'GSW', 'LAC']

In [6]:
# let's work with just San Antonio now
spurs_dfs = database['SAS']

In [7]:
# this is the per 36 minute dataframe. I want to use this in order
# to normalize based minutes played. 

spurs_dfs[6].head()

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Rk,,Age,G,GS,MP,FG,FGA,FG%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,1,Tim Duncan,22,50,50,1963,7.7,15.5,.495,0.0,...,.690,2.9,7.6,10.5,2.2,0.8,2.3,2.7,2.7,19.9
2,2,Avery Johnson,33,50,50,1672,4.7,9.9,.473,0.0,...,.568,0.5,2.1,2.5,7.9,1.1,0.2,2.4,2.2,10.5
3,3,David Robinson,33,49,49,1554,6.2,12.2,.509,0.0,...,.658,3.4,8.0,11.4,2.4,1.6,2.8,2.5,3.3,18.0
4,4,Sean Elliott,30,50,50,1509,5.0,12.1,.410,0.9,...,.757,0.8,4.2,5.1,2.8,0.6,0.4,1.7,2.5,13.4

__Column meanings for Per 36 Min table.__
___

Rk -- Rank

Age -- Age of Player at the start of February 1st of that season.

G -- Games

GS -- Games Started

MP -- Minutes Played

FG -- Field Goals Per 36 Minutes

FGA -- Field Goal Attempts Per 36 Minutes

FG% -- Field Goal Percentage

3P -- 3-Point Field Goals Per 36 Minutes

3PA -- 3-Point Field Goal Attempts Per 36 Minutes

3P% -- 3-Point Field Goal Percentage

2P -- 2-Point Field Goals Per 36 Minutes

2PA -- 2-Point Field Goal Attempts Per 36 Minutes

2P% -- 2-Point Field Goal Percentage

FT -- Free Throws Per 36 Minutes

FTA -- Free Throw Attempts Per 36 Minutes

FT% -- Free Throw Percentage

ORB -- Offensive Rebounds Per 36 Minutes

DRB -- Defensive Rebounds Per 36 Minutes

TRB -- Total Rebounds Per 36 Minutes

AST -- Assists Per 36 Minutes

STL -- Steals Per 36 Minutes

BLK -- Blocks Per 36 Minutes

TOV -- Turnovers Per 36 Minutes

PF -- Personal Fouls Per 36 Minutes

PTS -- Points Per 36 Minutes

In [4]:
# let's pull all per 36 min dfs

dfs_per_36 = {}

for team, dfs in database.items():
    clean_df = dfs[6].copy()
    clean_df.iloc[0,1] = 'Name'
    clean_df.columns = clean_df.iloc[0,:]
    clean_df.drop(0, inplace=True)
    clean_df.reset_index(inplace=True, drop=True)
    dfs_per_36[team] = clean_df
    
dfs_per_36[0]

NameError: name 'database' is not defined

In [6]:
# we also want the salaries for all the players
salaries = []

for team, dfs in database.items():
    new_df = dfs[-1].copy()
    new_df.iloc[0,1] = 'Name'
    new_df.columns = new_df.iloc[0, :]
    new_df.drop(0, inplace=True)
    new_df.reset_index(inplace=True, drop=True)
    salaries.append(new_df)
    
salaries

[0   Rk             Name       Salary
 0    1  Alonzo Mourning  $13,130,000
 1    2     Tim Hardaway   $5,600,000
 2    3   Jamal Mashburn   $5,033,000
 3    4       P.J. Brown   $4,480,000
 4    5      Dan Majerle   $3,290,000
 5    6    Voshon Lenard   $2,837,000
 6    7  Mark Strickland   $2,100,000
 7    8   Duane Causwell   $1,454,000
 8    9      Terry Mills   $1,145,000
 9   10     Terry Porter   $1,000,000
 10  11     Blue Edwards     $850,000
 11  12     Keith Askins     $725,000
 12  13     Marty Conlon     $662,500
 13  14      Rex Walters     $537,500, 0   Rk               Name      Salary
 0    1  Anfernee Hardaway  $8,505,000
 1    2       Horace Grant  $7,843,000
 2    3         Mark Price  $5,488,000
 3    4       Isaac Austin  $5,000,000
 4    5      Nick Anderson  $3,200,000
 5    6       Derek Strong  $3,000,000
 6    7  Darrell Armstrong  $2,900,000
 7    8     Gerald Wilkins  $2,000,000
 8    9         Yinka Dare  $1,657,000
 9   10          Bo Outlaw  $1,150,000
 10  11     Michael Doleac  $1,050,000
 11  12      Danny Schayes  $1,000,000
 12  13  Dominique Wilkins  $1,000,000
 13  14      Matt Harpring    $900,000
 14  15     B.J. Armstrong    $850,000
 15  16    Jonathan Kerner    $287,500
 16  17        Miles Simon    $287,500, 0   Rk              Name      Salary
 0    1       Matt Geiger  $6,800,000
 1    2      Theo Ratliff  $6,000,000
 2    3   Derrick Coleman  $5,600,000
 3    4       Tyrone Hill  $5,352,000
 4    5     Allen Iverson  $3,537,000
 5    6        Brian Shaw  $3,400,000
 6    7       Rex Walters  $1,625,000
 7    8       Aaron McKie  $1,430,000
 8    9      Larry Hughes  $1,330,000
 9   10       Rick Mahorn  $1,000,000
 10  11      George Lynch  $1,000,000
 11  12      Harvey Grant  $1,000,000
 12  13    Anthony Parker    $867,120
 13  14         Eric Snow    $846,300
 14  15      Doug Overton    $600,000
 15  16     Nazr Mohammed    $535,000
 16  17  Jerald Honeycutt    $300,000
 17  18        Casey Shaw    $287,500, 0   Rk              Name       Salary
 0    1     Patrick Ewing  $18,500,000
 1    2     Larry Johnson  $10,186,000
 2    3  Latrell Sprewell   $8,300,000
 3    4     Allan Houston   $7,000,000
 4    5      Chris Childs   $3,640,000
 5    6      Marcus Camby   $3,164,000
 6    7       Kurt Thomas   $1,750,000
 7    8     Buck Williams   $1,670,000
 8    9      Charlie Ward   $1,221,000
 9   10      Dennis Scott   $1,000,000
 10  11     Herb Williams   $1,000,000
 11  12     David Wingate   $1,000,000
 12  13    Mirsad Turkcan     $739,400
 13  14         Ben Davis     $425,000
 14  15      Rick Brunson     $350,000, 0   Rk               Name      Salary
 0    1     Kenny Anderson  $5,845,000
 1    2        Dana Barros  $3,500,000
 2    3         Greg Minor  $2,520,000
 3    4         Dino Radja  $2,500,000
 4    5     Pervis Ellison  $2,420,000
 5    6       Popeye Jones  $2,381,000
 6    7        Tony Battie  $2,238,000
 7    8     Antoine Walker  $2,107,000
 8    9         Ron Mercer  $2,033,000
 9   10   Vitaly Potapenko  $1,339,000
 10  11        Paul Pierce  $1,165,000
 11  12     Walter McCarty    $975,000
 12  13      Dontae' Jones    $953,856
 13  14  Dwayne Schintzius    $662,500
 14  15         Eric Riley    $537,500
 15  16        Bruce Bowen    $507,000
 16  17     Marlon Garnett    $287,500
 17  18        Damon Jones    $287,500, 0   Rk              Name       Salary
 0    1      Juwan Howard  $13,125,000
 1    2       Otis Thorpe   $4,400,000
 2    3   Calbert Cheaney   $4,000,000
 3    4    Mitch Richmond   $2,500,000
 4    5      Tracy Murray   $2,380,000
 5    6       Terry Davis   $1,750,000
 6    7     Chris Whitney   $1,440,000
 7    8        Tim Legler   $1,320,000
 8    9  Lorenzo Williams   $1,316,000
 9   10       Ben Wallace     $800,000
 10  11        John Coker     $350,000
 11  12      Jeff McInnis     $350,000
 12  13   Randell Jackson     $287,500, 0   Rk                Name       Salary
 0    1     Jayson Williams  $11,000,000
 1    2        Kendall Gill   $5,000,000
 2    3        Rony Seikaly   $4,252,000
 3    4       Jim McIlvaine   $4,200,000
 4    5      Keith Van Horn   $3,054,000
 5    6     Stephon Marbury   $2,562,000
 6    7        Michael Cage   $2,350,000
 7    8        Elliot Perry   $2,000,000
 8    9       Kerry Kittles   $1,762,000
 9   10        Eric Murdock   $1,750,000
 10  11      Lucious Harris   $1,680,000
 11  12       Scott Burrell   $1,000,000
 12  13          Chris Carr   $1,000,000
 13  14    Gheorghe Muresan     $475,000
 14  15        David Vaughn     $450,000
 15  16         Jamie Feick     $425,000
 16  17    Mark Hendrickson     $425,000
 17  18  William Cunningham     $350,000, 0   Rk              Name      Salary
 0    1         Rik Smits  $8,500,000
 1    2     Reggie Miller  $6,781,000
 2    3     Derrick McKey  $4,200,000
 3    4        Dale Davis  $4,038,000
 4    5      Mark Jackson  $3,600,000
 5    6      Chris Mullin  $3,510,000
 6    7     Antonio Davis  $3,500,000
 7    8       Travis Best  $2,750,000
 8    9        Jalen Rose  $2,145,000
 9   10       Sam Perkins  $1,785,000
 10  11  Haywoode Workman  $1,440,000
 11  12   Austin Croshere  $1,340,000
 12  13      Fred Hoiberg    $600,000
 13  14     Al Harrington    $543,000
 14  15         Mark Pope    $382,000
 15  16       Mate Skelin    $287,500, 0   Rk              Name       Salary
 0    1   Dikembe Mutombo  $11,218,000
 1    2       Steve Smith   $6,300,000
 2    3    Alan Henderson   $4,725,000
 3    4        Ken Norman   $3,775,000
 4    5   Mookie Blaylock   $3,600,000
 5    6        Grant Long   $2,977,000
 6    7     Tyrone Corbin   $2,400,000
 7    8    LaPhonso Ellis   $1,750,000
 8    9   Anthony Johnson   $1,000,000
 9   10         Mark West   $1,000,000
 10  11           Ed Gray     $832,440
 11  12    Roshown McLeod     $740,000
 12  13    Chris Crawford     $350,000
 13  14  Jeffrey Sheppard     $287,500, 0   Rk                Name      Salary
 0    1          Grant Hill  $6,675,000
 1    2  Christian Laettner  $5,360,000
 2    3          Bison Dele  $4,860,000
 3    4    Jerry Stackhouse  $3,887,000
 4    5          Loy Vaught  $3,830,000
 5    6      Lindsey Hunter  $2,050,000
 6    7       Eric Montross  $1,760,000
 7    8          Joe Dumars  $1,000,000
 8    9        Scot Pollard    $940,920
 9   10  Randolph Childress    $866,320
 10  11        Jud Buechler    $850,000
 11  12            Don Reid    $800,000
 12  13     Jerome Williams    $737,880
 13  14       Khalid Reeves    $475,000
 14  15    Charles O'Bannon    $320,000
 15  16      Korleone Young    $287,500, 0   Rk              Name      Salary
 0    1    Glenn Robinson  $6,380,000
 1    2     Chris Gatling  $4,266,000
 2    3    Scott Williams  $3,300,000
 3    4     Armen Gilliam  $3,244,000
 4    5       Sam Cassell  $3,000,000
 5    6     Ervin Johnson  $2,594,000
 6    7         Ray Allen  $2,320,000
 7    8        Tim Thomas  $1,856,000
 8    9   Vinny Del Negro  $1,750,000
 9   10    Robert Traylor  $1,590,000
 10  11        Dell Curry  $1,000,000
 11  12        Paul Grant    $903,240
 12  13  Haywoode Workman    $600,000
 13  14     Michael Curry    $550,000
 14  15     Adonis Jordan    $350,000, 0   Rk             Name      Salary
 0    1   Elden Campbell  $7,000,000
 1    2  Derrick Coleman  $6,667,000
 2    3    Anthony Mason  $4,165,000
 3    4     Bobby Phills  $3,480,000
 4    5      Eddie Jones  $2,200,000
 5    6     David Wesley  $2,160,000
 6    7         Joe Wolf  $1,000,000
 7    8     Chuck Person  $1,000,000
 8    9     Chucky Brown    $850,000
 9   10      Ricky Davis    $680,000
 10  11       Corey Beck    $425,000
 11  12      Brad Miller    $287,500, 0   Rk              Name       Salary
 0    1    Charles Oakley  $10,186,000
 1    2    Sharone Wright   $4,000,000
 2    3         Dee Brown   $3,750,000
 3    4  Micheal Williams   $2,975,000
 4    5     Doug Christie   $2,353,000
 5    6      Kevin Willis   $2,100,000
 6    7      Vince Carter   $1,760,000
 7    8     Tracy McGrady   $1,563,000
 8    9        B.J. Tyler   $1,411,000
 9   10      John Wallace   $1,021,000
 10  11   Michael Stewart   $1,000,000
 11  12       John Thomas     $737,000
 12  13     Negele Knight     $537,500
 13  14     Reggie Slater     $400,000
 14  15        Sean Marks     $287,500
 15  16       Paul Rogers     $287,500, 0   Rk              Name      Salary
 0    1        Shawn Kemp  $9,740,000
 1    2     Wesley Person  $4,200,000
 2    3       Danny Ferry  $4,000,000
 3    4          Bob Sura  $3,133,000
 4    5   Andrew DeClercq  $1,440,000
 5    6    Derek Anderson  $1,273,000
 6    7     Brevin Knight  $1,092,000
 7    8     Johnny Newman  $1,000,000
 8    9      Corie Blount    $537,500
 9   10   Mitchell Butler    $537,500
 10  11      Earl Boykins    $287,500
 11  12        Ryan Stack    $287,500
 12  13  Cedric Henderson    $250,000, 0   Rk             Name      Salary
 0    1       Ron Harper  $5,280,000
 1    2       Toni Kukoc  $4,610,000
 2    3      Brent Barry  $3,600,000
 3    4      Andrew Lang  $3,068,000
 4    5     Chuck Person  $2,860,000
 5    6      Mark Bryant  $2,050,000
 6    7      Randy Brown  $1,320,000
 7    8  Bill Wennington  $1,000,000
 8    9       Roy Rogers    $862,560
 9   10  Martin Muursepp    $763,200
 10  11      Keith Booth    $687,240
 11  12   Corey Benjamin    $540,000
 12  13     Jeff Sanders    $475,000
 13  14      Rusty LaRue    $350,000
 14  15      Bubba Wells    $312,000
 15  16        Cory Carr    $287,500
 16  17     Kornel David    $287,500
 17  18    Charles Jones    $287,500, 0   Rk              Name       Salary
 0    1    David Robinson  $14,841,000
 1    2      Sean Elliott   $5,333,000
 2    3     Charles Smith   $4,375,143
 3    4       Will Perdue   $4,373,000
 4    5        Tim Duncan   $3,413,000
 5    6     Avery Johnson   $3,000,000
 6    7   Antonio Daniels   $2,472,000
 7    8        Steve Kerr   $1,774,000
 8    9        Mario Elie   $1,750,000
 9   10     Jerome Kersey   $1,000,000
 10  11        Malik Rose     $425,000
 11  12       Andrew Gaze     $350,000
 12  13       Gerald King     $287,500
 13  14  Brandon Williams     $287,500, 0   Rk              Name      Salary
 0    1       Karl Malone  $6,142,000
 1    2     Greg Ostertag  $4,333,000
 2    3     John Stockton  $4,000,000
 3    4     Jeff Hornacek  $3,455,000
 4    5     Bryon Russell  $3,428,000
 5    6        Adam Keefe  $2,650,000
 6    7       Todd Fuller  $1,461,000
 7    8     Howard Eisley  $1,400,000
 8    9  Shandon Anderson  $1,300,000
 9   10      Thurl Bailey    $850,000
 10  11     Jacque Vaughn    $691,560
 11  12       Greg Foster    $588,000, 0 Rk               Name       Salary
 0  1    Hakeem Olajuwon  $12,943,000
 1  2     Scottie Pippen  $11,000,000
 2  3        Brent Price   $2,240,000
 3  4    Charles Barkley   $1,000,000
 4  5  Michael Dickerson     $949,600
 5  6         Bryce Drew     $857,000
 6  7           Sam Mack     $545,000
 7  8     Anthony Miller     $475,000
 8  9     Cuttino Mobley     $287,500, 0   Rk              Name       Salary
 0    1     Kevin Garnett  $14,000,000
 1    2   Terrell Brandon   $6,300,000
 2    3    Anthony Peeler   $2,254,000
 3    4      Dean Garrett   $2,160,000
 4    5         Joe Smith   $1,750,000
 5    6       Bill Curley   $1,544,000
 6    7       Malik Sealy   $1,000,000
 7    8     Bobby Jackson     $799,200
 8    9      Dennis Scott     $725,000
 9   10       Brian Evans     $686,780
 10  11    James Robinson     $537,500
 11  12  Andrae Patterson     $287,500
 12  13     Trevor Winter     $287,500, 0   Rk              Name      Salary
 0    1     Shawn Bradley  $6,750,000
 1    2    Michael Finley  $6,000,000
 2    3        A.C. Green  $5,125,088
 3    4       Robert Pack  $3,780,000
 4    5     Khalid Reeves  $2,002,000
 5    6  Erick Strickland  $1,920,000
 6    7  Hot Rod Williams  $1,750,000
 7    8     Samaki Walker  $1,619,880
 8    9     Dirk Nowitzki  $1,472,640
 9   10        Steve Nash  $1,190,760
 10  11        Gary Trent  $1,000,000
 11  12      Chris Anstey    $985,200
 12  13   Cedric Ceballos    $750,000
 13  14      Hubert Davis    $645,000
 14  15        Ansu Sesay    $287,500
 15  16      Bruno Sundov    $287,500, 0   Rk               Name      Salary
 0    1    Antonio McDyess  $9,000,000
 1    2       Bryant Stith  $4,666,000
 2    3      Eric Williams  $2,780,000
 3    4   Chauncey Billups  $2,742,000
 4    5      Raef LaFrentz  $2,150,000
 5    6      Nick Van Exel  $1,900,000
 6    7      Danny Fortson  $1,485,000
 7    8      Johnny Taylor  $1,037,000
 8    9         Keon Clark  $1,000,000
 9   10  Priest Lauderdale    $712,200
 10  11       Carl Herrera    $662,500
 11  12    Eric Washington    $520,000
 12  13        Loren Meyer    $450,000
 13  14      Kelly McCarty    $287,500, 0   Rk             Name      Salary
 0    1    Bryant Reeves  $7,222,000
 1    2     Bobby Hurley  $4,030,000
 2    3        Doug West  $2,915,000
 3    4       Mike Bibby  $2,400,000
 4    5    Michael Smith  $2,180,000
 5    6     Carl Herrera  $2,080,000
 6    7   Cherokee Parks  $2,000,000
 7    8     Doug Edwards  $1,625,000
 8    9     Lee Mayberry  $1,540,000
 9   10  Tony Massenburg    $900,000
 10  11    Pete Chilcutt    $700,000
 11  12   Rodrick Rhodes    $639,300
 12  13     Felipe Lopez    $600,000
 13  14     Terry Dehere    $537,500
 14  15     Marcus Brown    $500,000
 15  16     DeJuan Wheat    $350,000
 16  17   J.R. Henderson    $287,500
 17  18  Makhtar N'Diaye    $287,500, 0   Rk              Name      Salary
 0    1   Arvydas Sabonis  $9,000,000
 1    2  Damon Stoudamire  $9,000,000
 2    3   Rasheed Wallace  $9,000,000
 3    4       Brian Grant  $6,000,000
 4    5      Isaiah Rider  $4,810,000
 5    6     Stacey Augmon  $3,200,000
 6    7     Walt Williams  $3,000,000
 7    8     Carlos Rogers  $2,000,000
 8    9       Jim Jackson  $1,750,000
 9   10       Kelvin Cato  $1,149,000
 10  11       Bonzi Wells  $1,100,000
 11  12   Jermaine O'Neal  $1,075,000
 12  13      Greg Anthony  $1,000,000
 13  14        Gary Grant  $1,000,000
 14  15        Brian Shaw    $850,000
 15  16       John Crotty    $504,000
 16  17   Nikita Morgunov    $287,500, 0   Rk              Name       Salary
 0    1  Shaquille O'Neal  $15,000,000
 1    2         Glen Rice   $5,248,000
 2    3      Robert Horry   $5,000,000
 3    4    B.J. Armstrong   $2,800,000
 4    5     Travis Knight   $2,400,000
 5    6          Rick Fox   $1,750,000
 6    7        Sean Rooks   $1,680,000
 7    8      Corie Blount   $1,625,000
 8    9       Kobe Bryant   $1,319,000
 9   10      Derek Harper   $1,000,000
 10  11     Dennis Rodman   $1,000,000
 11  12      Derek Fisher     $795,000
 12  13         J.R. Reid     $780,000
 13  14   Ruben Patterson     $628,500
 14  15      Sam Jacobson     $559,000
 15  16        Tyronn Lue     $287,500, 0   Rk                 Name      Salary
 0    1        Tom Gugliotta  $7,800,000
 1    2        Danny Manning  $6,833,000
 2    3           Jason Kidd  $6,041,000
 3    4          Luc Longley  $4,000,000
 4    5    Clifford Robinson  $3,500,000
 5    6          Rex Chapman  $2,800,000
 6    7         Chris Morris  $1,000,000
 7    8           Joe Kleine  $1,000,000
 8    9       George McCloud    $750,000
 9   10          Pat Garrity    $740,000
 10  11  Horacio Llamas Grey    $425,000
 11  12          Marko Milic    $350,000
 12  13          Toby Bailey    $287,500
 13  14         Gerald Brown    $287,500
 14  15     Randy Livingston    $287,500, 0   Rk                Name       Salary
 0    1        Chris Webber  $10,000,000
 1    2         Vlade Divac   $8,300,000
 2    3      Lionel Simmons   $4,238,500
 3    4        Kevin Gamble   $1,645,000
 4    5      Jason Williams   $1,460,000
 5    6   Tariq Abdul-Wahad   $1,411,000
 6    7      Vernon Maxwell   $1,000,000
 7    8       Oliver Miller     $600,000
 8    9           Jon Barry     $600,000
 9   10        Terry Dehere     $575,000
 10  11  Corliss Williamson     $500,000
 11  12      Chris Robinson     $375,000
 12  13     Michael Hawkins     $350,000
 13  14        Scot Pollard     $350,000
 14  15        Jerome James     $287,500, 0   Rk               Name      Salary
 0    1        Gary Payton  $8,715,000
 1    2          Vin Baker  $4,264,000
 2    3     Hersey Hawkins  $3,644,000
 3    4    Detlef Schrempf  $3,333,000
 4    5        Don MacLean  $2,460,000
 5    6         Dale Ellis  $1,750,000
 6    7        Billy Owens  $1,750,000
 7    8     Olden Polynice  $1,000,000
 8    9        John Crotty    $600,000
 9   10     Aaron Williams    $575,000
 10  11  Vladimir Stepania    $543,000
 11  12         Craig Ehlo    $504,082
 12  13         Drew Barry    $350,000
 13  14     Moochie Norris    $350,000
 14  15      Rashard Lewis    $287,500
 15  16       Jelani McCoy    $287,500, 0   Rk              Name      Salary
 0    1  Donyell Marshall  $4,370,000
 1    2       John Starks  $4,000,000
 2    3      Jason Caffey  $3,675,000
 3    4       Chris Mills  $3,600,000
 4    5     Muggsy Bogues  $2,800,000
 5    6       Bimbo Coles  $2,000,000
 6    7    Antawn Jamison  $1,940,000
 7    8      Adonal Foyle  $1,701,000
 8    9    Felton Spencer  $1,650,000
 9   10     Erick Dampier  $1,538,000
 10  11     Duane Ferrell  $1,430,000
 11  12    Terry Cummings  $1,150,000
 12  13         Tony Delk  $1,131,000, 0   Rk                Name      Salary
 0    1    Stojko Vrankovic  $4,060,000
 1    2       Lamond Murray  $3,500,000
 2    3     Pooh Richardson  $3,030,000
 3    4       Rodney Rogers  $3,000,000
 4    5  Michael Olowokandi  $2,700,000
 5    6     Sherman Douglas  $2,200,000
 6    7     Lorenzen Wright  $1,923,000
 7    8      James Robinson  $1,800,000
 8    9     Eric Piatkowski  $1,650,000
 9   10         Keith Closs  $1,440,000
 10  11      Maurice Taylor  $1,209,000
 11  12       Charles Smith    $677,080
 12  13       Brian Skinner    $653,500
 13  14         Troy Hudson    $287,500
 14  15        Tyrone Nesby    $287,500]

In [7]:
len(salaries)*14 # i have 406 datapoints

406

In [8]:
# let's pickle the results

with open('per_36_min.pickle', 'wb') as f:
    pickle.dump(dfs_per_36, f)
    
with open('salaries.pickle', 'wb') as f:
    pickle.dump(salaries, f)